# Generated by Django 5.2.4 on 2026-05-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day_consumption', models.FloatField(verbose_name='Расход день, кВт·ч')),
                ('night_consumption', models.FloatField(verbose_name='Расход ночь, кВт·ч')),
                ('total_consumption', models.FloatField(verbose_name='Общий расход, кВт·ч')),
                ('total_cost', models.FloatField(verbose_name='Сумма к оплате, руб')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day_reading', models.FloatField(verbose_name='День (Т1), кВт·ч')),
                ('night_reading', models.FloatField(verbose_name='Ночь (Т2), кВт·ч')),
            ],
            options={
                'verbose_name': 'Показание счётчика',
                'verbose_name_plural': 'Показания счётчика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('day', 'День'), ('night', 'Ночь')], max_length=10)),
                ('range_num', models.IntegerField(verbose_name='Диапазон')),
                ('kwh', models.FloatField(verbose_name='Расход, кВт·ч')),
                ('tariff', models.FloatField(verbose_name='Тариф, руб')),
                ('cost', models.FloatField(verbose_name='Сумма, руб')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tns_electricity.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='current_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_bills', to='tns_electricity.meterreading'),
        ),
        migrations.AddField(
            model_name='bill',
            name='prev_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_bills', to='tns_electricity.meterreading'),
        ),
    ]
