# Generated by Django 5.2.4 on 2026-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_electricity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата показаний'),
        ),
    ]
