# Generated by Django 5.2.4 on 2026-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_electricity', '0002_meterreading_reading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='is_initial',
            field=models.BooleanField(default=False, verbose_name='Начальные показания'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
